### ISSUE TITLE
Trailing slash in traefik

### ISSUE THREAD

**Issue by robcxyz** [geometry-labs/icon-filter-registration#8]
https://github.com/traefik/traefik/issues/563#issuecomment-317236171

**Comment by shinyfoil** [comment]
So we have a couple options here. We can either manually put in the regex things into each route (which might be a pain to maintain eventually), or we can just make a note in the docs that if you're using something that doesn't automatically handle redirects (like curl), that you'll either have to put in the final "/" or you'll have to turn on redirects (in curl, it's -L).

I'm honestly inclined to go with the second option just from a maintainability standpoint. Like, the redirects are technically correct, it's just that curl doesn't immediately support them.

Thoughts, @robcxyz?

**Comment by robcxyz** [comment]
I think the regex rewrites would be a good thing to have around but if it is a pain, the trailing slash is fine.  Just document it.

**Comment by shinyfoil** [comment]
Closed in 2fd5085a881350aed255ca0307f5536af2098435
